name: Notes Test

on: push

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Test Build
    container:
      image: ghcr.io/boomanaiden154/notes:latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Test Build
        run: python3 gensite.py
